import requests
import hashlib
import time
import sys
import re

sys.stdout.reconfigure(encoding='utf-8')

PANEL_URL = "http://74.48.191.162:8888"
USER = "gw7htyhf"
PASS = "s6wZnTJfjS"

def login_and_upload():
    s = requests.Session()
    
    # 1. Get Login Page (to get salt/token if needed, though bt usually uses static hashing logic on frontend)
    print("Connecting...")
    try:
        s.get(f"{PANEL_URL}/login", timeout=5)
    except Exception as e:
        print(f"Connect Error: {e}")
        return

    # 2. Login Logic
    # Baota Password Hash: md5(md5(pass) + '_bt.cn')
    m5 = hashlib.md5()
    m5.update(PASS.encode('utf-8'))
    p1 = m5.hexdigest()
    
    m5 = hashlib.md5()
    m5.update((p1 + '_bt.cn').encode('utf-8'))
    p_final = m5.hexdigest()
    
    payload = {
        "username": USER,
        "password": p_final,
        "code": "",
        "token": ""
    }
    
    print("Logging in...")
    r = s.post(f"{PANEL_URL}/login", data=payload)
    res_json = r.json()
    
    if res_json.get('status') == True:
        print("Login Success!")
    else:
        print(f"Login Failed: {res_json}")
        return

    # 3. Read Local HTML
    with open('csl-live-site/index_quantum_fixed.html', 'r', encoding='utf-8') as f:
        html_content = f.read()

    # 4. Upload via File Manager API
    # SaveFileBody path=/www/wwwroot/hsapi.xyz/full.html
    print("Uploading UI to full.html...")
    upload_data = {
        'path': '/www/wwwroot/hsapi.xyz/full.html',
        'data': html_content,
        'encoding': 'utf-8'
    }
    
    r = s.post(f"{PANEL_URL}/files?action=SaveFileBody", data=upload_data)
    print(f"Upload Response: {r.text}")

    # 5. Also upload API data while we are at it
    print("Uploading Data to api.json...")
    # Read the data generated by the daemon (we assume it ran once or we fetch it? No, we can't fetch.
    # I will just write a dummy JSON to test the pipe first)
    dummy_json = '[{"id":1,"home":{"sc":"测试队"},"away":{"sc":"客队"},"score":"1-1","status":{"sc":"进行中"},"time":"12:00"}]'
    
    upload_data_json = {
        'path': '/www/wwwroot/hsapi.xyz/api.json',
        'data': dummy_json,
        'encoding': 'utf-8'
    }
    r = s.post(f"{PANEL_URL}/files?action=SaveFileBody", data=upload_data_json)
    print(f"JSON Upload Response: {r.text}")

if __name__ == "__main__":
    login_and_upload()
